[package]
name = "sandstorm-collections-app"
version = "1.3.0"
authors = ["David Renshaw <david@sandstorm.io>"]
build = "build.rs"
edition = "2018"

[[bin]]

name = "server"
path = "src/main.rs"

[build-dependencies]
capnpc = "0.11"

[dependencies]
futures = "0.3"
capnp = "0.11"
capnp-rpc = "0.11"
rustc-serialize = "0.3.19"
url = "1.2"
sandstorm = "0.0.10"
futures-tokio-compat = { git = "https://github.com/dwrensha/futures-tokio-compat", branch = "tokio-0.2" }
tokio = { version = "0.2.6", features = ["net", "rt-util", "time", "uds"]}
multipoll = { git = "https://github.com/dwrensha/multipoll" }
